# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
notifications:
  email: false
sudo: false
addons:
    apt_packages:
        - gfortran
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'VERSION < v"0.7-" || using Pkg; Pkg.clone(pwd()); Pkg.build("ReverseDiffSparse"); Pkg.test("ReverseDiffSparse"; coverage=true)'
after_success:
  - julia -e 'VERSION < v"0.7-" || using Pkg; cd(Pkg.dir("ReverseDiffSparse")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
